from src.utils.constants import (
    DEFAULT_CHROMA_DIR,
    DEFAULT_COURSES_PATH,
    DEFAULT_OUTPUT_PATH,
    DEFAULT_POLICIES_PATH,
    DEFAULT_PROGRAM_PATH,
    PROCESSED_DATA_DIR,
)


DEFAULT_COURSE_FILE = DEFAULT_COURSES_PATH
DEFAULT_PROGRAM_FILE = DEFAULT_PROGRAM_PATH
DEFAULT_POLICY_FILE = DEFAULT_POLICIES_PATH
DEFAULT_PLAN_OUTPUT_FILE = DEFAULT_OUTPUT_PATH
DEFAULT_GRADIO_HISTORY_FILE = PROCESSED_DATA_DIR / "gradio_chat_history.json"
